name: "Infra Pipeline"

on: workflow_dispatch
jobs:
  terraform-job:
      runs-on: self_hosted
      steps:
        - name: checkout
          uses: actions/checkout@v5.0.0
          
                  
            
